### ISSUE TITLE
Build fails when using via carthage..

### ISSUE THREAD

**Issue by dearprakash** [ReactiveKit/ReactiveUIKit#1]
....
....
**\* Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcworkspace
**\* Building scheme "ReactiveFoundation-OSX" in ReactiveFoundation.xcworkspace
**\* WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed
**\* Building scheme "ReactiveFoundation-iOS" in ReactiveFoundation.xcworkspace
**\* Building scheme "ReactiveUIKit-iOS" in ReactiveUIKit.xcworkspace
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “7483NBERMM” were found.
A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

**Comment by dearprakash** [comment]
Sorry for false alarm. 

I am testing to use ReactiveKit in a blank project and report with more details if i continue to have this issue.

**Comment by srdanrasic** [comment]
@dearprakash, were you able to solve it or does it still happen?

**Comment by dearprakash** [comment]
Weirdly i can not reproduce this error which was mentioned  [above](https://github.com/ReactiveKit/ReactiveUIKit/issues/1#issue-118360483)

Trying to build on an empty project just with Reactive[Kit/UI/Foundation] succeeded first time.

When i tried to use ReactiveKit on a project that already had some other frameworks ,
 'carthage update --platform iOS'  failed while building ReactiveUIKit.xcworkspace
with following:

The following build commands failed:
    Check dependencies
(1 failure)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
Code Sign error: ad hoc code signing not allowed with SDK 'iOS 9.1'
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.1'
A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

Naively running the command (carthage update --platform iOS) again succeeded :| 

I am not sure any of this is helpful..
