### ISSUE TITLE
ReactiveUIKit .gitmodules causing cloning issues

### ISSUE THREAD

**Issue by adamstener** [ReactiveKit/ReactiveUIKit#10]
It appears the .gitmodules is not allowing the cloning of this repo.

This is failing with git clone and with Carthage.

**Comment by srdanrasic** [comment]
Same as https://github.com/ReactiveKit/ReactiveFoundation/issues/4.

**Comment by srdanrasic** [comment]
With release of v2, submodules are no longer being used. ReactiveKit dependency should be handled with CocoaPods or Carthage or developer must ensure ReactiveKit is present in workspace.
