### ISSUE TITLE
Carthage build for v2.0.0-beta3 fails

### ISSUE THREAD

**Issue by RMRMesquita** [ReactiveKit/ReactiveUIKit#11]
Carthage build fails

carthage update --platform iOS
**\* Fetching ReactiveUIKit
**\* Fetching ReactiveKit
**\* Checking out ReactiveKit at "v2.0.0-beta3"
**\* Checking out ReactiveUIKit at "v2.0.0-beta3"
**\* xcodebuild output can be found in /var/folders/ly/m88lkldd54q1n_sq03v1dr8m0000gn/T/carthage-xcodebuild.mF4gRB.log
**\* Building scheme "ReactiveKit-iOS" in ReactiveKit.xcworkspace
**\* Building scheme "ReactiveUIKit-iOS" in ReactiveUIKit.xcworkspace
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIControl.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UITextField.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UITextView.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UISegmentedControl.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIImageView.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UINavigationItem.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIActivityIndicatorView.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
.../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift:25:8: error: no such module 'ReactiveKit'
A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIBarItem.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIControl.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UITextField.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UITextView.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UISegmentedControl.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIImageView.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UINavigationItem.swift
    CompileSwift normal arm64 .../testJSONParsing/Carthage/Checkouts/ReactiveUIKit/Sources/UIActivityIndicatorView.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(9 failures)

carthage version
0.15.2
xcodebuild -version
Xcode 7.3
Build version 7D175

**Comment by lutzj82** [comment]
It is also failing for me too.  Looks like using Package.swift is the reason why this won't build.
Its not able to reference ReactiveKit.  I was able to open the workspace and build manually...but i guess through Carthage it can't find the ReactiveKit module.

**Comment by srdanrasic** [comment]
Hi @lutzj82, why do you think this is affected by Package.swift?

**Comment by srdanrasic** [comment]
HI @RMRMesquita, @lutzj82, Carthage should be working now in beta5. Thanks!
