### ISSUE TITLE
Swift 3 Compatible Version

### ISSUE THREAD

**Issue by JettF** [ReactiveKit/ReactiveUIKit#14]
Any idea when ReactiveUIKit will be migrated to Swift 3?

**Comment by srdanrasic** [comment]
Hi @JettF! With ReactiveKit 3, Bond framework should be used for bindings. It has everything that ReactiveUIKit had. Please check out [migration section](https://github.com/ReactiveKit/ReactiveKit#migration).

**Comment by JettF** [comment]
I will check it out. Thanks!
