### ISSUE TITLE
Make UITable/UICollectionView have multiple sections

### ISSUE THREAD

**Issue by thebarndog** [ReactiveKit/ReactiveUIKit#2]
Right now the binding helper on `UITableView` and `UICollectionView` only allows for one section with multiple items, which is incredibly restricting. It **should** be able to let the consumer to having multiple sections with multiple headers and footers as they deem necessary>

This ties in with [this issue](https://github.com/ReactiveKit/ReactiveKit/issues/9), where `ObservableCollection` should propagate events from sub-arrays of `ObservableCollections` up to the parent observer. The binding helper should take in either `ObservableCollection<[ObservableCollection<[Model]>]>` or `ObservableCollection<[[Model]]>` and either pass in the whole collection to the cell creation function or just the sub-array at that index, whether that's an array of `Model` objects or an observable collection of `Model` objects.

**Comment by srdanrasic** [comment]
I agree that we need support for multiple sections. I'm adding this as a TODO.

There is not need to propagate events to superclass though. We don't want the update of a single row to cause whole section refresh. Please check out explanation here: https://github.com/ReactiveKit/ReactiveKit/issues/9. Thanks!

**Comment by mtaweel** [comment]
Is multiple sections table supported, or not yet?

**Comment by srdanrasic** [comment]
@mtaweel yes, but you have to use ReactiveKit 3 + Bond 5.
https://github.com/ReactiveKit/Bond#observable2darray--mutableobservable2darray

ReactiveUIKit has been replaced with Bond:
https://github.com/ReactiveKit/ReactiveKit#migration-from-v2x-to-v30

**Comment by mtaweel** [comment]
@srdanrasic Thanks 👍
